/* This file was generated by SableCC (http://www.sablecc.org/). */

package memlang.syntax.analysis;

import java.util.*;
import memlang.syntax.node.*;

public class AnalysisAdapter implements Analysis
{
    private Hashtable<Node,Object> in;
    private Hashtable<Node,Object> out;

    @Override
    public Object getIn(Node node)
    {
        if(this.in == null)
        {
            return null;
        }

        return this.in.get(node);
    }

    @Override
    public void setIn(Node node, Object o)
    {
        if(this.in == null)
        {
            this.in = new Hashtable<Node,Object>(1);
        }

        if(o != null)
        {
            this.in.put(node, o);
        }
        else
        {
            this.in.remove(node);
        }
    }

    @Override
    public Object getOut(Node node)
    {
        if(this.out == null)
        {
            return null;
        }

        return this.out.get(node);
    }

    @Override
    public void setOut(Node node, Object o)
    {
        if(this.out == null)
        {
            this.out = new Hashtable<Node,Object>(1);
        }

        if(o != null)
        {
            this.out.put(node, o);
        }
        else
        {
            this.out.remove(node);
        }
    }

    @Override
    public void caseStart(Start node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAInstsProgram(AInstsProgram node)
    {
        defaultCase(node);
    }

    @Override
    public void caseATargetPrecondition(ATargetPrecondition node)
    {
        defaultCase(node);
    }

    @Override
    public void caseASizePrecondition(ASizePrecondition node)
    {
        defaultCase(node);
    }

    @Override
    public void caseADeclarationInst(ADeclarationInst node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAAssignInst(AAssignInst node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAWaitInst(AWaitInst node)
    {
        defaultCase(node);
    }

    @Override
    public void caseASetInst(ASetInst node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAPrintInst(APrintInst node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAAssertInst(AAssertInst node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAStopInst(AStopInst node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAMultipleIds(AMultipleIds node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAFindOper(AFindOper node)
    {
        defaultCase(node);
    }

    @Override
    public void caseANarrowOper(ANarrowOper node)
    {
        defaultCase(node);
    }

    @Override
    public void caseALtSign(ALtSign node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAGtSign(AGtSign node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAGeSign(AGeSign node)
    {
        defaultCase(node);
    }

    @Override
    public void caseALeSign(ALeSign node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAEqualsSign(AEqualsSign node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAExecute(AExecute node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTSemi(TSemi node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTComma(TComma node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTEquals(TEquals node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTNEquals(TNEquals node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTWAssign(TWAssign node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTAssign(TAssign node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTLe(TLe node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTLt(TLt node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTGe(TGe node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTGt(TGt node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTPlus(TPlus node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTMinus(TMinus node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTStar(TStar node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTSlash(TSlash node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTPercent(TPercent node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTNot(TNot node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTLBrace(TLBrace node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTRBrace(TRBrace node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTLPar(TLPar node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTRPar(TRPar node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTOr(TOr node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTAnd(TAnd node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTEol(TEol node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTWhile(TWhile node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTFind(TFind node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTField(TField node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTSet(TSet node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTWait(TWait node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTAssert(TAssert node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTNarrow(TNarrow node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTPrint(TPrint node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTTarget(TTarget node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTSize(TSize node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTExec(TExec node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTStop(TStop node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTString(TString node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTNumber(TNumber node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTComment(TComment node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTBlank(TBlank node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTId(TId node)
    {
        defaultCase(node);
    }

    @Override
    public void caseEOF(EOF node)
    {
        defaultCase(node);
    }

    @Override
    public void caseInvalidToken(InvalidToken node)
    {
        defaultCase(node);
    }

    public void defaultCase(@SuppressWarnings("unused") Node node)
    {
        // do nothing
    }
}
