/* This file was generated by SableCC (http://www.sablecc.org/). */

package memlang.syntax.node;

import java.util.*;
import memlang.syntax.analysis.*;

@SuppressWarnings("nls")
public final class AAssertInst extends PInst
{
    private TAssert _assert_;
    private final LinkedList<PMultipleIds> _ids_ = new LinkedList<PMultipleIds>();
    private TId _id_;

    public AAssertInst()
    {
        // Constructor
    }

    public AAssertInst(
        @SuppressWarnings("hiding") TAssert _assert_,
        @SuppressWarnings("hiding") List<?> _ids_,
        @SuppressWarnings("hiding") TId _id_)
    {
        // Constructor
        setAssert(_assert_);

        setIds(_ids_);

        setId(_id_);

    }

    @Override
    public Object clone()
    {
        return new AAssertInst(
            cloneNode(this._assert_),
            cloneList(this._ids_),
            cloneNode(this._id_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAssertInst(this);
    }

    public TAssert getAssert()
    {
        return this._assert_;
    }

    public void setAssert(TAssert node)
    {
        if(this._assert_ != null)
        {
            this._assert_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._assert_ = node;
    }

    public LinkedList<PMultipleIds> getIds()
    {
        return this._ids_;
    }

    public void setIds(List<?> list)
    {
        for(PMultipleIds e : this._ids_)
        {
            e.parent(null);
        }
        this._ids_.clear();

        for(Object obj_e : list)
        {
            PMultipleIds e = (PMultipleIds) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._ids_.add(e);
        }
    }

    public TId getId()
    {
        return this._id_;
    }

    public void setId(TId node)
    {
        if(this._id_ != null)
        {
            this._id_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._id_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._assert_)
            + toString(this._ids_)
            + toString(this._id_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._assert_ == child)
        {
            this._assert_ = null;
            return;
        }

        if(this._ids_.remove(child))
        {
            return;
        }

        if(this._id_ == child)
        {
            this._id_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._assert_ == oldChild)
        {
            setAssert((TAssert) newChild);
            return;
        }

        for(ListIterator<PMultipleIds> i = this._ids_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PMultipleIds) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        if(this._id_ == oldChild)
        {
            setId((TId) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
