/* This file was generated by SableCC (http://www.sablecc.org/). */

package memlang.syntax.node;

import memlang.syntax.analysis.*;

@SuppressWarnings("nls")
public final class AStopInst extends PInst
{
    private TStop _stop_;
    private TId _id_;

    public AStopInst()
    {
        // Constructor
    }

    public AStopInst(
        @SuppressWarnings("hiding") TStop _stop_,
        @SuppressWarnings("hiding") TId _id_)
    {
        // Constructor
        setStop(_stop_);

        setId(_id_);

    }

    @Override
    public Object clone()
    {
        return new AStopInst(
            cloneNode(this._stop_),
            cloneNode(this._id_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAStopInst(this);
    }

    public TStop getStop()
    {
        return this._stop_;
    }

    public void setStop(TStop node)
    {
        if(this._stop_ != null)
        {
            this._stop_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._stop_ = node;
    }

    public TId getId()
    {
        return this._id_;
    }

    public void setId(TId node)
    {
        if(this._id_ != null)
        {
            this._id_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._id_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._stop_)
            + toString(this._id_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._stop_ == child)
        {
            this._stop_ = null;
            return;
        }

        if(this._id_ == child)
        {
            this._id_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._stop_ == oldChild)
        {
            setStop((TStop) newChild);
            return;
        }

        if(this._id_ == oldChild)
        {
            setId((TId) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
