/* This file was generated by SableCC (http://www.sablecc.org/). */

package memlang.syntax.node;

import memlang.syntax.analysis.*;

@SuppressWarnings("nls")
public final class AWaitInst extends PInst
{
    private TWait _wait_;
    private TNumber _number_;

    public AWaitInst()
    {
        // Constructor
    }

    public AWaitInst(
        @SuppressWarnings("hiding") TWait _wait_,
        @SuppressWarnings("hiding") TNumber _number_)
    {
        // Constructor
        setWait(_wait_);

        setNumber(_number_);

    }

    @Override
    public Object clone()
    {
        return new AWaitInst(
            cloneNode(this._wait_),
            cloneNode(this._number_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAWaitInst(this);
    }

    public TWait getWait()
    {
        return this._wait_;
    }

    public void setWait(TWait node)
    {
        if(this._wait_ != null)
        {
            this._wait_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._wait_ = node;
    }

    public TNumber getNumber()
    {
        return this._number_;
    }

    public void setNumber(TNumber node)
    {
        if(this._number_ != null)
        {
            this._number_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._number_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._wait_)
            + toString(this._number_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._wait_ == child)
        {
            this._wait_ = null;
            return;
        }

        if(this._number_ == child)
        {
            this._number_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._wait_ == oldChild)
        {
            setWait((TWait) newChild);
            return;
        }

        if(this._number_ == oldChild)
        {
            setNumber((TNumber) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
