/* This file was generated by SableCC (http://www.sablecc.org/). */

package memlang.syntax.node;

import memlang.syntax.analysis.*;

@SuppressWarnings("nls")
public final class TAddress extends Token
{
    public TAddress()
    {
        super.setText("add");
    }

    public TAddress(int line, int pos)
    {
        super.setText("add");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TAddress(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTAddress(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TAddress text.");
    }
}
