/* This file was generated by SableCC (http://www.sablecc.org/). */

package memlang.syntax.node;

import memlang.syntax.analysis.*;

@SuppressWarnings("nls")
public final class TAgent extends Token
{
    public TAgent()
    {
        super.setText("agent");
    }

    public TAgent(int line, int pos)
    {
        super.setText("agent");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TAgent(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTAgent(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TAgent text.");
    }
}
