/* This file was generated by SableCC (http://www.sablecc.org/). */

package memlang.syntax.node;

import memlang.syntax.analysis.*;

@SuppressWarnings("nls")
public final class TExec extends Token
{
    public TExec()
    {
        super.setText("exec");
    }

    public TExec(int line, int pos)
    {
        super.setText("exec");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TExec(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTExec(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TExec text.");
    }
}
