/* This file was generated by SableCC (http://www.sablecc.org/). */

package memlang.syntax.node;

import memlang.syntax.analysis.*;

@SuppressWarnings("nls")
public final class TFind extends Token
{
    public TFind()
    {
        super.setText("find");
    }

    public TFind(int line, int pos)
    {
        super.setText("find");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TFind(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTFind(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TFind text.");
    }
}
