/* This file was generated by SableCC (http://www.sablecc.org/). */

package memlang.syntax.node;

import memlang.syntax.analysis.*;

@SuppressWarnings("nls")
public final class TInterpretorEscape extends Token
{
    public TInterpretorEscape()
    {
        super.setText("$?$");
    }

    public TInterpretorEscape(int line, int pos)
    {
        super.setText("$?$");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TInterpretorEscape(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTInterpretorEscape(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TInterpretorEscape text.");
    }
}
