/* This file was generated by SableCC (http://www.sablecc.org/). */

package memlang.syntax.node;

import memlang.syntax.analysis.*;

@SuppressWarnings("nls")
public final class TListen extends Token
{
    public TListen()
    {
        super.setText("listen");
    }

    public TListen(int line, int pos)
    {
        super.setText("listen");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TListen(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTListen(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TListen text.");
    }
}
