/* This file was generated by SableCC (http://www.sablecc.org/). */

package memlang.syntax.node;

import memlang.syntax.analysis.*;

@SuppressWarnings("nls")
public final class TNarrow extends Token
{
    public TNarrow()
    {
        super.setText("narrow");
    }

    public TNarrow(int line, int pos)
    {
        super.setText("narrow");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TNarrow(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTNarrow(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TNarrow text.");
    }
}
