/* This file was generated by SableCC (http://www.sablecc.org/). */

package memlang.syntax.node;

import memlang.syntax.analysis.*;

@SuppressWarnings("nls")
public final class TPattern extends Token
{
    public TPattern()
    {
        super.setText("pattern");
    }

    public TPattern(int line, int pos)
    {
        super.setText("pattern");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TPattern(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTPattern(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TPattern text.");
    }
}
