/* This file was generated by SableCC (http://www.sablecc.org/). */

package memlang.syntax.node;

import memlang.syntax.analysis.*;

@SuppressWarnings("nls")
public final class TPlayLang extends Token
{
    public TPlayLang()
    {
        super.setText("pl");
    }

    public TPlayLang(int line, int pos)
    {
        super.setText("pl");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TPlayLang(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTPlayLang(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TPlayLang text.");
    }
}
