/* This file was generated by SableCC (http://www.sablecc.org/). */

package memlang.syntax.node;

import memlang.syntax.analysis.*;

@SuppressWarnings("nls")
public final class TTarget extends Token
{
    public TTarget()
    {
        super.setText("target");
    }

    public TTarget(int line, int pos)
    {
        super.setText("target");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TTarget(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTTarget(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TTarget text.");
    }
}
